Pin button in gridstack items
voila-dashboards/voila-gridstack pull request #116
Opened 2021-03-26 15:34 UTC by hbcarlos

Solves #110 

Seams that the `locked` option is not working perfectly. When an item is pinned we can't move/resize it either.

![pinned](https://user-images.githubusercontent.com/26092748/112654900-2ab58880-8e50-11eb-9795-072b7db688bc.gif)

Question: How should we indicate the item is pinned or not? 🤔

2021-03-28 12:47 UTC, hbcarlos commented
Metadata format changes with this PR, notebooks without attribute `locked` in metadata will be reset if they are open with the editor. This is also the reason why the test fails.

I'm not sure if this is the right way of attaching the toolbar: 
https://github.com/voila-dashboards/voila-gridstack/blob/83bf90e67d550c531c08dfd5e4624859b26dffab/packages/jupyterlab-gridstack/src/editor/gridstack/item.tsx#L42

The latest changes look like this:
![locked](https://user-images.githubusercontent.com/26092748/112752487-9c6a0f80-8fd3-11eb-90f2-9157c0b46ea9.gif)

2021-03-30 09:34 UTC, fcollonval commented
Nice work!

> I'm not sure if this is the right way of attaching the toolbar

I would suggest taking a approach similar to the file browser using a `create` function.

https://github.com/jupyterlab/jupyterlab/blob/98ccafa1e1b188e852fabb581d5d3f6aad38020e/packages/filebrowser/src/listing.ts#L216

https://github.com/jupyterlab/jupyterlab/blob/98ccafa1e1b188e852fabb581d5d3f6aad38020e/packages/filebrowser/src/listing.ts#L1761

It can be nice to set the grid item content as `Panel` rather than HTML node and add two children: the toolbar and the cell.

You can add a [`SingletonLayout`](https://jupyterlab.github.io/lumino/widgets/classes/singletonlayout.html) on GridStackItem and add to it the panel.

2021-05-04 16:24 UTC, hbcarlos commented
Thanks for the advice!

I'm not sure how to implement the layout.

2021-05-05 07:33 UTC, hbcarlos commented
On my last PR, I created a model for items and added signals to communicate changes to the grid.

The idea would be to do a refactor to improve the items and reduce the number of signals for items in `GridStackModel`, creating a single signal to track changes on items changing the `cellRemoved` signal for something like this:

https://github.com/voila-dashboards/voila-gridstack/blob/01bcd2f264b9c0268d815750520c261b9ec37747/packages/jupyterlab-gridstack/src/editor/gridstack/model.ts#L62

```TypeScript
enum ItemState {
  CLOSED,
  LOCKED,
  UNLOCKED
}

interface ItemChange {
   item: GridStackItemModel;
   change: ItemState;
}
```
```TypeScript
this._itemStateChanged = new Signal<this, ItemChange>(this);
```

What are your thoughts? Feedback is welcome!

2021-05-05 13:07 UTC, fcollonval reviewed
Thanks for pushing on this one @hbcarlos 

It looks almost good. I have a small concern about the item model life cycle and its connection to the toolbar rendering.

2021-07-29 07:09 UTC, fcollonval requested changes
I went through the latest changes @hbcarlos 
I have minor comments that should be easy to tackle.

2021-07-29 07:09 UTC, fcollonval commented on packages/jupyterlab-gridstack/src/editor/item/toolbar.tsx
> +            <unPinIcon.react height="16px" width="16px" />
You should avoid hard coding styles (bad practice). Instead you should add a common class to all buttons and set the svg size using that class and CSS rules.

2021-07-29 07:09 UTC, fcollonval commented on packages/jupyterlab-gridstack/src/editor/item/toolbar.tsx
> +          <div className="pin" onClick={() => this._model.unlock()}>
It is better to use meaningful html tag; in this case `button` instead of `div`.

2021-07-29 07:18 UTC, hbcarlos commented
Hey, thanks for the review! I'll change today.

2021-07-29 17:14 UTC, fcollonval approved these changes
Thanks @hbcarlos LGTM

2021-08-04 14:09 UTC, merged